### ISSUE TITLE
Remove social.homunyan.com from blocklist

### ISSUE THREAD

**Issue by rainyday** [dzuk-mutant/blockchain#1]
social.homunyan.com is listed as hosting lolicon described here as "illustrated child pornography".

social.homunyan.com does not host illustrated child pornography so it should not be blocked using this reason.

**Comment by dzuk-mutant** [comment]
My use of 'lolicon' might be a bit misleading and not really describe in total what I use the tag for.

The way I use it is a broader category than the label I use implies because pornography is somewhat relative and I don't just block what might be considerred outright pornography. I will do the same with sexually suggestive imagery involving what appears to be a minor because it generally falls under the same umbrella as something that might be more explicit (as I had found with user ZettaiRyouiki to give an example, post/update #4632, now seems to be deleted). If I find that kind of stuff, I also find that grounds enough for blocklisting, especially when the admin boosts it.

I will rename this tag and clarify it more, so I'm sorry for the poor choice of wording on my part.

If this instance has gone under a management or policy change (which I wouldn't be aware of), then we can talk about it, but if it is still posting that kind of content, then it will need to stay, unfortunately. :/

**Comment by rainyday** [comment]
Unclear what "appears to be a minor" means in this situation. We don't allow sexualized pictures of children, but at the same time, I'm not going to remove any PG-13 drawing I see because someone might personally feel that a certain art style, such as anime, looks "too young."

**Comment by dzuk-mutant** [comment]
I know that anime has that particular style thing going on sometimes (but Japan generally does have a cultural contingent with sexualised depictions of minors, and I've known people who do these kinds of illustrations, so I know it's also not an accident).

Whether or not additional contextualisation, text, etc. claims that an individual in a picture is an adult, if they *appear* to be underage, we have a legal obligation to block this stuff.

**Comment by deutrino** [comment]
I've read your README for this project, the FAQ, and the human-readable blocklist, and can find no support for your assertion that "we have a legal obligation to block this stuff."

What stuff, precisely? I can find no objective criteria in the documents I read.
