### ISSUE TITLE
Remove "NP-" and "FVZ" on niu.moe

### ISSUE THREAD

**Issue by Technowix** [dzuk-mutant/blockchain#5]
Hello !

**Non-proactive** (NP-) mean, on niu.moe at least, that we don't do something before they happens, like if there is someone know in the past for making nasty stuff, we aren't digging old things and give to this person the ability to repent if the actual person is trying to be a better one.
So it have nothing to do with your actual description of Non-proactive here, since we don't wait for another admins to complain before taking action.

**Fascist speech / Violent speech / Zero-moderation.** (FVZ) First, I would be grateful to not insult us and our community.
Second, our ToS / CoC is agaisn't all you listed about us. 
Our following of the [humans rights](http://www.ohchr.org/EN/UDHR/Documents/UDHR_Translations/eng.pdf) is against all the "ideologies" you [listed here](https://github.com/dzuk-mutant/blockchain#fvz-w-a-fvz).

You can still put us in you blocklist, but remove those reasons since they are false, thanks.

Edit : I'm a bit harsh because I haven't read the "human version" first, but in our discussions I think you misunderstood what I was trying to say when I see this label on us :(

**Comment by dzuk-mutant** [comment]
Look, I've already told you about instances of people posting bigoted and shitty content in your instance. It doesn't really matter what's in your ToS if this is a thing that continues to happen.

If you want to deal with them in a way that actually makes it obvious that niu.moe doesn't have a lot of nasty stuff anymore, we can talk, but otherwise, this isn't really productive.
